### ISSUE TITLE
Error while creating channel "peer channel create"

### ISSUE THREAD

**Issue by seshanthS** [seshanthS/blockchain#1]
The command used is ,
`root@3d92ae31ce8c:/opt/gopath/src/github.com/hyperledger/fabric/peer# peer channel create -o orderer.univ.in:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel.tx --tls --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/univ.in/msp/tlscacerts/tlsca.univ.in-cert.pem`

> Error: got unexpected status: BAD_REQUEST -- Attempted to include a member which is not in the consortium.

**Comment by blockchainguyy** [comment]
Hi @seshanthS , I'm experiencing a similar issue: i have detailed it here: https://stackoverflow.com/questions/57144745/cannot-create-channels-with-new-orgs-in-fabric-got-error-attempted-to-include

Can you please help me?
